app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.brand_list, name='brands'),
    path('add_brand/', views.add_brand, name='add_brand'),
    path('edit_brand/<int:pk>/', views.edit_brand, name='edit_brand'),
    path('delete/<int:pk>/', views.delete_brand, name='delete_brand'),
    path('brand_detail/<int:pk>/', views.brand_detail_view, name='brand_detail'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('brands/', include('app.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_page, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('home/', views.home, name='home'),
]

app/models.py
from django.db import models
from django.contrib.auth import get_user_model
# from users.models import Owner

User = get_user_model()


class Brand(models.Model):
    name = models.CharField(max_length=150)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    manager = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='manager')

    def __str__(self):
        return self.name

class Menu(models.Model):
    name = models.CharField(max_length=150)
    note = models.TextField(blank=True, null=True)
    items = models.ManyToManyField("Items")
    def __str__(self):
        return self.name


class Outlet(models.Model):
    name = models.CharField(max_length=150)
    menu = models.ForeignKey("Menu", on_delete=models.SET_NULL, null=True, blank=True, related_name='outlet')
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, blank=True, null=True)
    staff = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return f'{self.name} | {self.brand.name}'


class Items(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager


class CustomUserManager(BaseUserManager):

    def create_superuser(self, email, password, **other_fields):

        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must be assigned to is_superuser=True.')

        return self.create_user(email, password, **other_fields)

    def create_user(self, email, password, **other_fields):

        if not email:
            raise ValueError('You must provide an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, **other_fields)
        user.set_password(password)
        user.is_active = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    
    USER_TYPE_CHOICES = (
        (1, 'AC_Owner'),
        (2, 'Manager'),
        (3, 'Staff'),
        (4, 'Customer'),
    )
    email = models.EmailField(unique=True)
    user_type = models.PositiveSmallIntegerField(choices=USER_TYPE_CHOICES, null=True, blank=True)
    first_name = models.CharField(max_length=150, blank=True, null=True)
    last_name = models.CharField(max_length=150, blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email

app/forms.py
from dataclasses import field
from django import forms
from django.forms import ModelForm
from app.models import Brand, Items, Outlet, Menu


class BrandForm(ModelForm):

    class Meta:
        model = Brand
        fields = ['name', 'manager']

app/views.py
from django.shortcuts import redirect, render
from app.models import Brand, Outlet, Items, Menu
from django.contrib.auth.decorators import login_required
from app.forms import BrandForm
from django.contrib.auth import get_user_model

User = get_user_model()

@login_required
def brand_list(request):
    
    brands = Brand.objects.filter(owner=request.user)
    # outlets = Outlet.objects.all()
    context = {'brands': brands,}

    return render(request, 'brand_page.html', context)

@login_required
def add_brand(request):

    form = BrandForm()
    if request.method == 'POST':
        form = BrandForm(request.POST)
        user = request.user
        if form.is_valid():
            brand = form.save(commit=False)
            brand.owner = user
            brand.save()
            print(brand)
            return redirect('brands')

    context = {'form': form, 'add': True}
    return render(request, 'add_brand.html', context)

@login_required
def edit_brand(request, pk):

    brand = Brand.objects.get(pk=pk)
    form = BrandForm(instance=brand)
    if request.method == 'POST':
        form = BrandForm(request.POST, instance=brand)
        if form.is_valid():
            brand.save()
            print(brand)
            return redirect('brands')

    context = {'form': form, 'brand_name': brand.name}
    return render(request, 'add_brand.html', context)

@login_required()
def delete_brand(request, pk):
    brand = Brand.objects.get(id=pk)
    if request.method == 'POST':
        brand.delete()
        return redirect('brands')
    context = {'item': brand}
    return render(request, 'delete.html', context)

@login_required
def brand_detail_view(request, pk):

    brand = Brand.objects.get(pk=pk)
    outlets = Outlet.objects.filter(brand=brand)
    # menus = Menu.objects.all()
    context = {'brand': brand, 'outlets': outlets,}

    return render(request, 'brand_detail.html', context)

users/views.py
import django
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import get_user_model, login, logout, authenticate
from django.contrib.auth.decorators import login_required
from app.models import Brand

User = get_user_model()


@login_required
def home(request):
    return render(request, 'home.html')

def login_page(request):

    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)

        # AC_Owner login
        if user.user_type == 1:
            login(request, user)
            return redirect('brands')

        # Brand Manager
        elif user.user_type == 2:
            login(request, user)
            brand = Brand.objects.get(manager=user)
            return HttpResponseRedirect(reverse('brand_detail', kwargs={'pk': brand.pk}))

        # staff user
        elif user.user_type == 3:
            login(request, user)
            return redirect('home')
        
        # superuser login
        elif user.is_superuser:
            login(request, user)
            return redirect('home')
        else:
            HttpResponse('Username or password is incorrect!')
    context = {}
    return render(request, 'login.html')

@login_required
def logout_user(request):
    logout(request)
    return redirect('login')

templates/add_brand.html
{% extends 'base.html' %}
{% block title_block %} Add Brand {% endblock %}
{% block body_block %}
<center>
    {% if add %}
    <h1>Add a new brand</h1>
    {% else %}
    <h1>Edit {{brand_name}}</h1>
    {% endif %}
</center>
<div class="col-sm-6 mx-auto m-2">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Add</button>
    </form>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    {% block css_block %}

    {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>{% block title_block %} {% endblock %}</title>
  </head>
  <body>
    
    {% block body_block %}

    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/brand_detail.html
{% extends 'base.html' %}
{% block title_block %} {{brand.name}} {% endblock %}
{% block body_block %}
<center><h1>{{brand.name}}</h1><br>
  <h3>List of Outlets</h3></center>
  <div class="col-sm-6 mx-auto m-2">
      <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Outlet name</th>
              <th scope="col">Staff</th>
              <th scope="col"><a link="#">Menus</a></th>
              <th scope="col">Edit</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for outlet in outlets %}
            <tr>
              <th scope="row">#</th>
              <td>{{outlet.name}}</td>
              <td>{{outlet.staff.first_name}}</td>
              <td>{{outlet.menu.name}}
                <a class="btn btn-success btn-sm" href="#" role="button">Add</a>
              </td>
              <td><a class="btn btn-primary" href="{% url 'edit_brand' pk=brand.id %}" role="button">Edit</a></td>
              <td><a class="btn btn-danger" href="{% url 'delete_brand' pk=brand.id %}" role="button">Delete</a></td>
            </tr>
            {% endfor %}
          </tbody>
          <a class="btn btn-success" href="{% url 'add_brand' %}" role="button">Add</a> | 
          <a class="btn btn-info" href="{% url 'brands' %}" role="button">Back</a> | 
          <a class="btn btn-secondary" href="{% url 'logout' %}" role="button">{{request.user.first_name}}-Logout</a>
        </table>
  </div>
{% endblock %}

templates/brand_page.html
{% extends 'base.html' %}
{% block title_block %} Brand {% endblock %}
{% block body_block %}
<center><h1>Brand Page</h1><br>
  <h3>List of Brands</h3></center>
  <div class="col-sm-6 mx-auto m-2">
      <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Brand name</th>
              <th scope="col">Manager</th>
              <th scope="col"><a link="#">Outlets</a></th>
              <th scope="col">Edit</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
            {% for brand in brands %}
            <tr>
              <th scope="row">1</th>
              <td>{{brand.name}}</td>
              <td>{{brand.manager.first_name}}</td>
              <td>
                <ul>
                  {% for outlet in brand.outlet_set.all %}
                  <li><a href="#">{{outlet}}</a></li>
                  {% endfor %}
                </ul>
                <a class="btn btn-success btn-sm" href="#" role="button">Add</a>
              </td>
              <td><a class="btn btn-primary" href="{% url 'edit_brand' pk=brand.id %}" role="button">Edit</a></td>
              <td><a class="btn btn-danger" href="{% url 'delete_brand' pk=brand.id %}" role="button">Delete</a></td>
            </tr>
            {% endfor %}
          </tbody>
          <a class="btn btn-success" href="{% url 'add_brand' %}" role="button">Add</a> | 
          <a class="btn btn-secondary" href="{% url 'logout' %}" role="button">{{request.user.first_name}}-Logout</a>
        </table>
  </div>
{% endblock %}

templates/delete.html
{% extends 'base.html' %}
{% block body_block %}
<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <p>Are you sure you want to delete {{item}}</p>
                <form action="{% url 'delete_brand' item.id %} " method="POST">
                {% csrf_token %}
                <a class="btn btn-primary" href="{% url 'brands' %}">Cancel</a><br>
                <br>
                <input class="btn btn-danger" type="submit" name="Submit">
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    Logged in! <br>

    <a href="{% url 'logout' %}">Log out</a>?
</body>
</html>

templates/login.html
{% extends 'base.html' %}
{% block title_block %} Login {% endblock %}
{% block body_block %}
<center><h1>Log in form</h1></center>
<div class="col-sm-6 mx-auto m-5">
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Email address</label>
      <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input type="password" name="password" class="form-control" id="exampleInputPassword1">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock%}